# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 16:24
from __future__ import unicode_literals

import builtins
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('Mobis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField('Bus', 'area', models.PositiveIntegerField()),
        migrations.AlterField('Station', 'area', models.PositiveIntegerField()),
        migrations.AlterField('Map', 'area', models.PositiveIntegerField()),

        migrations.RenameField(
            model_name='Bus',
            old_name='area',
            new_name='community',
        ),
        migrations.RenameField(
            model_name='Station',
            old_name='area',
            new_name='community',
        ),
        migrations.RenameField(
            model_name='Map',
            old_name='area',
            new_name='community',
        ),
        migrations.RenameModel('Area', 'Community'),

        migrations.AlterField('bus', 'community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busses', to='Mobis.Community')),
        migrations.AlterField('station', 'community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='Mobis.Community')),
        migrations.AlterField('map', 'community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='Mobis.Community')),

        migrations.AddField(
            model_name='community',
            name='uid',
            field=models.PositiveIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]


