"""
 Copyright © 2025 IAV GmbH Ingenieurgesellschaft Auto und Verkehr, All Rights Reserved.
 
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 
 http://www.apache.org/licenses/LICENSE-2.0
 
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 
 SPDX-License-Identifier: Apache-2.0
"""
# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 16:24
from __future__ import unicode_literals

import builtins
from django.db import migrations, models
import django.db.models.deletion

def link_buses(apps, schema_editor):
    Route = apps.get_model('Mobis', 'Route')
    Bus = apps.get_model('Mobis', 'Bus')
    for route in Route.objects.all().iterator():
        bus = Bus.objects.get(uid=route.busId)
        route.bus = bus
        route.save()

def unlink_buses(apps, schema_editor):
    Route = apps.get_model('Mobis', 'Route')
    for route in Route.objects.all().iterator():
        route.busId = route.bus.uid
        route.save()

def default_uid(apps, schema_editor):
    Station = apps.get_model('Mobis', 'Station')
    for station in Station.objects.all().iterator():
        station.uid = station.id
        station.save()
def reverse_default_uid(apps, schema_editor):
    Station = apps.get_model('Mobis', 'Station')
    for station in Station.objects.all().iterator():
        station.uid = 0


class Migration(migrations.Migration):

    dependencies = [
        ('Mobis', '0001_initial'),
        ('Mobis', '0002_area2community_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='bus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='Mobis.Bus'),
            preserve_default=False,
        ),
        migrations.RunPython(link_buses, unlink_buses),
        migrations.RemoveField(
            model_name='route',
            name='busId',
        ),

        migrations.AddField(
            model_name='bus',
            name='latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='longitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='group_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        
        migrations.AddField(
            model_name='station',
            name='uid',
            field=models.PositiveIntegerField(default=None, unique=False, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(default_uid, reverse_default_uid),
        migrations.AlterField(
            model_name='station',
            name='uid',
            field=models.PositiveIntegerField(unique=True),
        ),

        migrations.AlterField(
            model_name='station',
            name='mapId',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
