# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mobis', '0003_linkRouteBus_addFields'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='finished_on',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='started_on',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='hopOffNode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hopOffs', to='Mobis.Node'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hopOnNode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hopOns', to='Mobis.Node'),
        ),
    ]
