# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobis', '0004_startedon_finishedon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='finished_on',
        ),
        migrations.RemoveField(
            model_name='route',
            name='started_on',
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('DRF', 'Draft'), ('BKD', 'Booked'), ('FRZ', 'Frozen'), ('STR', 'Started'), ('FNS', 'Finished')], default='DRF', max_length=3),
        ),
    ]
