"""
 Copyright © 2025 IAV GmbH Ingenieurgesellschaft Auto und Verkehr, All Rights Reserved.
 
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 
 http://www.apache.org/licenses/LICENSE-2.0
 
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 
 SPDX-License-Identifier: Apache-2.0
"""
# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobis', '0005_auto_20190305_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='community',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='community',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='community',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
