# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobis', '0005_auto_20190305_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='community',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='community',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='community',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
