# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobis', '0006_auto_20190415_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='community',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
