# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobis', '0008_route_community'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.AlterField(
            model_name='bus',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
