# Generated by Django 2.0 on 2022-02-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobis', '0011_bus_wheelchairs_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
