# Generated by Django 2.0 on 2022-06-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobis', '0012_node_lat_lon_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['uid']},
        ),
        migrations.AlterField(
            model_name='node',
            name='mapId',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
