# Generated by Django 4.2.10 on 2024-02-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobis', '0013_auto_20220616_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='vehicleType',
            field=models.CharField(default='bus', max_length=256, null=True),
        ),
    ]
